# Generated by Django 4.1.13 on 2023-11-28 04:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0004_course_students"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Videos",
            new_name="Video",
        ),
    ]
